name: "Web"

on:
  push:
    branches:
      - main
    paths:
      - "src/web"
      - ".github/workflows/web-docker.yml"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./src/web
          file: ./src/web/Dockerfile
          push: true
          tags: amorimdub/udagram-web:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
